name: Automatic Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-go@v5
      with:
        go-version: 1.18

    - run: go test -coverprofile=coverage.txt ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: se-dev-pion/functools

    - run: go tool cover -html=coverage.txt -o cover.html
    - run: rm coverage.txt
    - uses: actions/upload-artifact@v4
      with:
        name: ut-coverage
        path: ./cover.html

