name: Automatic Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-go@v5
      with:
        go-version: 1.18

    - run: go test -coverprofile=cover.out ./...
    - run: go tool cover -html=cover.out -o cover.html
    - run: rm cover.out
    - uses: actions/upload-artifact@v4
      with:
        name: ut-coverage
        path: ./cover.html
